name: Test_and_build_artifacts_on_main

on:
  push:
    branches:
      - 'main'

env:
  DEBUG_KEYSTORE_PASSWORD: ${{ secrets.DEBUG_KEYSTORE_PASSWORD }}
  DEBUG_SIGN_KEY_ALIAS: ${{ secrets.DEBUG_SIGN_KEY_ALIAS }}
  DEBUG_SIGN_KEY_PASSWORD: ${{ secrets.DEBUG_SIGN_KEY_PASSWORD }}

jobs:
  build_apk_aab:
    name: Build dev artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Build dev APK and AAB after test
        run: |
          ./gradlew test
          ./gradlew assembleDev
          ./gradlew bundleDev
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-dev.apk
          path: app/build/outputs/apk/dev/app-dev.apk
      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-dev.aab
          path: app/build/outputs/bundle/dev/app-dev.aab
