name: Test_and_build_artifacts_on_test

on:
  push:
    branches:
      - 'test'

env:
  RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

jobs:
  build_apk_aab:
    name: Build test artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Build test APK and AAB after test
        run: |
          ./gradlew test
          ./gradlew assembleQa
          ./gradlew bundleQa
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-test.apk
          path: app/build/outputs/apk/qa/app-qa.apk
      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-test.aab
          path: app/build/outputs/bundle/qa/app-qa.aab
